name: ci
on:
  push:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_MIRROR: https://docker.mirrors.ustc.edu.cn
    steps:
      - uses: actions/checkout@v3
      - name: 配置国内Docker镜像
        run: |
          sudo mkdir -p /etc/docker
          echo '{"registry-mirrors":["https://docker.mirrors.ustc.edu.cn"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - uses: docker/setup-qemu-action@v2
      - uses: catwrt/build-action@main
